### PR TITLE
Migrate from CircleCI to GitHub Actions

### PR DESCRIPTION
**Pull request by eggplants**
[Test](https://github.com/eggplants/MonkeyType/actions/workflows/test.yml)

```markdown
[![Test](https://github.com/eggplants/MonkeyType/actions/workflows/test.yml/badge.svg)](https://github.com/eggplants/MonkeyType/actions/workflows/test.yml)
```

https://github.com/eggplants/MonkeyType/actions

### CODE REVIEW

**Comment by eggplants** [comment]
https://app.circleci.com/pipelines/github/Instagram/MonkeyType/94/workflows/f78ae979-74f1-4973-be16-ea3426250ad5

image

https://github.com/eggplants/MonkeyType/actions/runs/2030361973

image

**Comment by carljm** [comment]
This looks good to me! Why does the signal box still show CircleCI failing and GitHub Actions not running?

**Comment by carljm** [comment]
Oh I guess CircleCI is still configured to run somewhere in the settings, or maybe on the CircleCI side, so I'll have to disable that. And maybe enable GitHub Actions to run automatically also. I see that the summary shows manual run succeeding. Looks good, thank you!

**Comment by eggplants** [comment]
Please try to stop building from CircleCI Setting: `Project Settings > Overview > Stop Building`

**Comment by carljm** [comment]
Yeah I don't actually have admin access to do that myself, but I've pinged the people who should be able to take care of it. Thanks!

**Pull request merged**
