### PR TITLE
Improve the default code filter's correctness and performance.

### PR DESCRIPTION
**Pull request by vodik**
We need to fully resolve the filename when deciding to filter code because of possible discrepancies that might arise with symlinks (e.g. `/lib64` is symlinked to `/lib` - see #33).

Added a cache around the default filter as well since its essentially pure and adding symlink resolution created an incredibly large performance overhead. Fortunately, with the cache in place, this tool performs even faster than without the patch.

### CODE REVIEW

**Comment by vodik** [comment]
I need to step away for a bit, but I'm looking into how I broke `_frozen_importlib` filtering.

**Comment by carljm** [comment]
I would guess it broke because they aren't real paths and pathlib does something weird. Probably should move that handling out of `LIB_PATHS` and special-case it inside the filter instead. Otherwise this looks good!

**Comment by vodik** [comment]
I adjusted it to just drop anything that leads with a '<', so we'll ignore everything that doesn't have a source file associated with it. I don't know how you can meaningfully hint the result of runtime generated code.

**Comment by carljm** [comment]
Looks great! Thanks for paying attention to performance.

**Comment by vodik** [comment]
Looking at this again, as a heads up, I think its probably going to make sense to up the lru_cache maxsize, the 128 default quickly gets exhausted rather quickly.

**Comment by carljm** [comment]
Yeah... hard to pick a value since it depends on the size of the codebase being traced. Maybe I'll try setting it at 8192 for now;. The cache should be pretty memory-efficient, it's just a mapping of a hash to a boolean.

**Pull request merged**
